### ISSUE TITLE
Blank save when saving an imported game from clipboard. 

### ISSUE THREAD

**Issue by znichola** [novitchis/Chessman#4]
So I like to use this program to save games I find in comments or videos. I will copy the moves then import from clipboard into chessman. That all works, I then save this new game, that also completes without errors. The problem is that the file saved is empty. A workaround I found was to do a different last move than re-do the correct one, for whatever reason saving after this results in a normal save file. 

Nor sure if your still working on this, I though I would post anyway. 

Incidentally I tried to contribute but could not figure out how to build the project without getting a bunch of errors. I tried I used visualstudio 2017 community edition, and the team explorer to copy the git files. I tried the options that come up with the solution solutions and folder, chessman.sln and it's directory. For chessman.sln I got over 1000 errors when trying to build a solution. Something is badly configured and I'm too much of a beginner to figure out what. I don't really want to waste your time if you've moved on from the project so don't feel obliged to spend loads of time on this.

**Comment by znichola** [comment]
WOO, I managed to get it to build and run! Had to change build setting processor, to specify x64 and follow instructions on how to solve one of the errors.

**Comment by novitchis** [comment]
Hello, thanks for posting this issue. I could reproduce it.
The current behavior is to save the game up to the current move. If there is no selection it will save nothing.
I think this is wrong, we should always save the whole game.
I will gladly approve a pull request if you want to change this behavior.
Use [Gitter Chat](https://gitter.im/ChessmanDev/Lobby) if you have any questions.
